version: '2.1'
services:

  web:
    build: .

    ports:
      - "5000:5000"

    volumes:
      - .:/code

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: wget http://localhost:5000/ -O -
      interval: 12s
      timeout: 3s
      retries: 3

  redis:
    image: "redis:alpine"

    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3

